

name: auth

on:
  pull_request:
    paths: "/auth/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - run: cd auth && npm run i && npm run test
        
